swagger: "2.0"
info:
  version: "0.2"
  title: Swagger definition of Coderbot API v2

consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/v2"

# Paths supported by the server application
paths:
  /stop:
    post:
      operationId: "api.stop"
      summary: "Summary"
      description: "Description"
      responses:
        200:
          description: "Successful read people list operation"