swagger: "2.0"
info:
  version: "0.2"
  title: Swagger definition of Coderbot API v2

consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/v2"

# Paths supported by the server application
paths:
  /list:
    get:
      operationId: "api.list"
      summary: "Get the list of all the saved programs"
      tags:
        - Program management
      responses:
        200:
          description: "ok"
  /load:
    get:
      operationId: "api.load"
      summary: "Get the program with the specified ID"
      tags:
        - Program management
      responses:
        200:
          description: "ok"
  /save:
    post:
      operationId: "api.save"
      summary: "Save a new program"
      tags:
        - Program management
      parameters:
        - in: body
          name: data
          schema:
            type: object
      responses:
        200:
          description: "ok"
  /exec:
    post:
      operationId: "api.exec"
      summary: "Execute the given program"
      tags:
        - Program management
      parameters:
        - in: body
          name: data
          schema:
            type: object
      responses:
        200:
          description: "ok"
  /status:
    get:
      operationId: "api.status"
      summary: "Bot general informations and execution status"
      tags:
        - Status informations
      responses:
        200:
          description: "Bot status"
  /stop:
    post:
      operationId: "api.stop"
      summary: Stops the bot motors
      tags:
        - Direct control
      responses:
        200:
          description: "Successfully stopped the motors"
  /move:
    post:
      summary: Moves the bot forward or backward.
      operationId: "api.move"
      tags:
        - Direct control
      parameters:
        - in: body
          name: data
          description: Movement speed and duration
          schema:
            type: object
            default: {'speed': 100, 'elapse':-1}
            required:
              - speed
              - elapse
            properties:
              speed:
                type: number
                description: 0 to 100 represent a forward movement (100 being the maximum speed), while 0 to -100 is a backward movement (-100 being the maximu speed)
              elapse:
                type: number
                description: Duration of the movement. -1 moves the bot until a /stop command is received.
      responses:
        200:
          description: Sent command to the bot GPIO.
  /turn:
    post:
      summary: Make a turn with the motors
      operationId: "api.turn"
      tags:
        - Direct control
      parameters:
        - in: body
          name: data
          description: Turn
          schema:
            type: object
            default: {'speed': -80, 'elapse':-1}
            required:
              - speed
              - elapse
            properties:
              speed:
                type: number
                description: 0 to 100 represent a forward movement (100 being the maximum speed), while 0 to -100 is a backward movement (-100 being the maximu speed)
              elapse:
                type: number
                description: Duration of the movement. -1 moves the bot until a /stop command is received.
      responses:
        201:
          description: Sent command to the bot GPIO.