# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: coderbot/python-gpac:3.5-tf2
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #    - v1-dependencies-{{ checksum "requirements_stub.txt" }}
      #    # fallback to using the latest cache if no exact match is found
      #    - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_stub.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements_stub.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export PYTHONPATH=./stub:test
            mkdir test-reports
            python3 -m unittest test/coderbot_test.py 2>&1 | tee test-reports/test_report.txt
            python3 -m unittest test/cnn_test.py 2>&1 | tee test-reports/test_report.txt
            python3 -m unittest test/camera_test.py 2>&1 | tee test-reports/test_report.txt
            echo "test complete"
      - store_artifacts:
          path: test-reports/
          destination: tr1

      - store_test_results:
          path: test-reports/

