#!/bin/sh

### BEGIN INIT INFO
# Provides:          pigpiod
# Required-Start:    udev
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# X-Interactive:
# Description: PI GPIO Server
# Short-Description: Provides access to GPIO to non-root users
### END INIT INFO

PATH='/sbin:/bin:/usr/bin'

NAME=pigpiod
PIGPIOD=/usr/local/bin/pigpiod
FIND_PID="ps -eo pid,args | grep /usr/local/bin/pigpiod | awk '{print $1}'"

RET=0

. /lib/lsb/init-functions

kill_pid () {
    PID=$(eval $FIND_PID)
    if [ ! -z $PID ]; then
        kill $PID
        PID=$(eval $FIND_PID)
        if [ ! -z $PID ]; then
            sleep 3
            kill -9 $PID
        fi
    fi
}

case "$1" in
    start|reload|restart|force-reload)
    	kill_pid
	log_daemon_msg "Starting PIGPIO Daemon" "pigpiod"
	echo
    	$PIGPIOD
    	RET=$?
        ;;
    stop)
    	kill_pid
    	RET=$?
        ;;
    status)
        ;;
    *)
    	log_failure_msg "Usage: /etc/init.d/$NAME {start|stop|restart}"
    	RET=1
        ;;
esac

exit $RET

:
